apiVersion: v1
kind: Pod
metadata:
  name: env-pod
spec:
  containers:
    - name: env-pod
      image: nginx
      env:
      - name: env_1
        value: "valor1"
      - name: env_2
        value: "valor2"